// <auto-generated />
using System;
using AIDev.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIDev.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220210512_AddArchitectAgent")]
    partial class AddArchitectAgent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AIDev.Api.Models.AgentReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("AlignmentScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletenessScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DevRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesAlignmentScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuggestedPriority")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DevRequestId");

                    b.ToTable("AgentReviews");
                });

            modelBuilder.Entity("AIDev.Api.Models.ArchitectReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Approach")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DevRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstimatedComplexity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedEffort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesAnalysed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilesReadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanFeedback")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Step1CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step1PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step2CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step2PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDurationMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DevRequestId");

                    b.ToTable("ArchitectReviews");
                });

            modelBuilder.Entity("AIDev.Api.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DevRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DevRequestId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("AIDev.Api.Models.DevRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualBehavior")
                        .HasColumnType("TEXT");

                    b.Property<int>("AgentReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedBehavior")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GitHubIssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubIssueUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAgentReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastArchitectReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepsToReproduce")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedByEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DevRequests");
                });

            modelBuilder.Entity("AIDev.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubOwner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubRepo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitHubOwner", "GitHubRepo")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AIDev.Api.Models.RequestComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArchitectReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DevRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAgentComment")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentReviewId");

                    b.HasIndex("ArchitectReviewId");

                    b.HasIndex("DevRequestId");

                    b.ToTable("RequestComments");
                });

            modelBuilder.Entity("AIDev.Api.Models.AgentReview", b =>
                {
                    b.HasOne("AIDev.Api.Models.DevRequest", "DevRequest")
                        .WithMany("AgentReviews")
                        .HasForeignKey("DevRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevRequest");
                });

            modelBuilder.Entity("AIDev.Api.Models.ArchitectReview", b =>
                {
                    b.HasOne("AIDev.Api.Models.DevRequest", "DevRequest")
                        .WithMany("ArchitectReviews")
                        .HasForeignKey("DevRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevRequest");
                });

            modelBuilder.Entity("AIDev.Api.Models.Attachment", b =>
                {
                    b.HasOne("AIDev.Api.Models.DevRequest", "DevRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("DevRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevRequest");
                });

            modelBuilder.Entity("AIDev.Api.Models.DevRequest", b =>
                {
                    b.HasOne("AIDev.Api.Models.Project", "Project")
                        .WithMany("Requests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AIDev.Api.Models.RequestComment", b =>
                {
                    b.HasOne("AIDev.Api.Models.AgentReview", "AgentReview")
                        .WithMany("Comments")
                        .HasForeignKey("AgentReviewId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDev.Api.Models.ArchitectReview", "ArchitectReview")
                        .WithMany("Comments")
                        .HasForeignKey("ArchitectReviewId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDev.Api.Models.DevRequest", "DevRequest")
                        .WithMany("Comments")
                        .HasForeignKey("DevRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentReview");

                    b.Navigation("ArchitectReview");

                    b.Navigation("DevRequest");
                });

            modelBuilder.Entity("AIDev.Api.Models.AgentReview", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("AIDev.Api.Models.ArchitectReview", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("AIDev.Api.Models.DevRequest", b =>
                {
                    b.Navigation("AgentReviews");

                    b.Navigation("ArchitectReviews");

                    b.Navigation("Attachments");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("AIDev.Api.Models.Project", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
